AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
    BucketName:
        Type: String
    CodeKey:
        Type: String
    
Resources:
    MyFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python2.7
            CodeUri:
              Bucket: !Ref BucketName
              Key: !Ref CodeKey
            Policies:
              - LambdaInvokePolicy:
                FunctionName:
                  Ref: FunctionNameParam
              - Version: '2012-10-17' # CloudTrail Policy Document
                Statement:
                  - Effect: Allow
                    Action:
                      - cloudtrail:StartLogging
                    Resource: 'arn:aws:cloudtrail:*:*:trail/*'

            Events:
              CloudWatchEvent1:
                Type: CloudWatchEvent
                Properties:
                  Pattern:
                    detail-type:
                      - AWS API Call via CloudTrail
                    source:
                      - aws.cloudtrail
                    detail:
                      eventSource:
                        - cloudtrail.amazonaws.com
                      eventName:
                        - StopLogging          